language: java
before_install:
  # https://docs.travis-ci.com/user/encrypting-files/#Encrypting-multiple-files
  - openssl aes-256-cbc -K $encrypted_380c8ce0181b_key -iv $encrypted_380c8ce0181b_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - cp telegram.properties src/main/resources/telegram.properties
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install -y kubectl google-cloud-sdk google-cloud-sdk-app-engine-java
before_script:
  - gcloud auth activate-service-account "travis-ci@growbit-0.iam.gserviceaccount.com" --key-file=travis-cigrowbit-52554fcb00cd.json
  - gcloud config set project growbit-0
script:
  - mvn test -B
  - mvn appengine:update -Dappengine.additionalParams="--service_account_json_key_file=travis-cigrowbit-52554fcb00cd.json"
after_script:
  - appengine_version=$(grep -oPm1 "(?<=<version>)[^<]+" <<< cat src/main/webapp/WEB-INF/appengine-web.xml)
  - gcloud app services set-traffic default --splits ${appengine_version}=1 --migrate --quiet --verbosity info
